import Link from "next/link";
import {
  ArrowRight,
  CalendarDays,
  CheckCircle2,
  Clock3,
  LayoutGrid,
  Link2,
  MessageSquareMore,
  Sparkles,
  Video,
  Wand2,
} from "lucide-react";

const featureCards = [
  {
    icon: CalendarDays,
    title: "Smart availability",
    description:
      "Publish polished booking pages with dynamic slots that update in real time as your calendar fills.",
  },
  {
    icon: Clock3,
    title: "Timezone aware",
    description:
      "Every guest sees the right time instantly, removing confusion before they hit book.",
  },
  {
    icon: Link2,
    title: "Shareable booking links",
    description:
      "Send one branded link anywhere and let clients book without email threads or follow-up friction.",
  },
  {
    icon: MessageSquareMore,
    title: "Instant confirmations",
    description:
      "Autogenerated confirmations keep everyone aligned with clear next steps and booking details.",
  },
  {
    icon: Wand2,
    title: "Calendar automation",
    description:
      "Buffer rules, reminders, and scheduling logic stay in sync so your availability stays accurate.",
  },
  {
    icon: LayoutGrid,
    title: "Brandable workflows",
    description:
      "Tailor the booking experience with premium visual styling that feels native to your product.",
  },
];

const integrationBullets = [
  "Two-way Google Calendar sync keeps every event aligned.",
  "Google Meet links are generated automatically at booking time.",
  "Availability updates immediately when meetings move or cancel.",
];

function BookingVisual() {
  return (
    <div className="relative mx-auto w-full max-w-5xl">
      <div className="absolute -inset-6 rounded-[2rem] bg-[radial-gradient(circle_at_top_left,rgba(99,102,241,0.28),transparent_45%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,0.22),transparent_40%)] blur-2xl" />
      <div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950/85 shadow-[0_30px_100px_rgba(2,6,23,0.45)] backdrop-blur">
        <div className="flex items-center justify-between border-b border-white/10 px-5 py-4 text-xs text-slate-400 sm:px-6">
          <div className="flex items-center gap-2.5 text-slate-200">
            <span className="flex size-8 items-center justify-center rounded-full bg-white/10 text-[0.65rem] font-semibold tracking-[0.2em] text-white">
              C
            </span>
            <span>MeetMint live booking</span>
          </div>
          <span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1 text-emerald-300">
            Google Calendar connected
          </span>
        </div>

        <div className="grid gap-0 lg:grid-cols-[1.2fr_0.8fr]">
          <div className="border-b border-white/10 p-5 sm:p-6 lg:border-b-0 lg:border-r">
            <div className="mb-4 flex items-center justify-between text-sm text-slate-300">
              <div>
                <p className="font-medium text-white">Availability snapshot</p>
                <p className="mt-1 text-slate-400">Friday, June 14</p>
              </div>
              <div className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-slate-300">
                8 open slots
              </div>
            </div>

            <div className="grid gap-4 sm:grid-cols-[0.9fr_1.1fr]">
              <div className="rounded-[1.5rem] border border-white/10 bg-white/5 p-4">
                <div className="mb-4 flex items-center justify-between">
                  <div>
                    <p className="text-xs uppercase tracking-[0.25em] text-slate-500">
                      Upcoming
                    </p>
                    <p className="mt-1 text-sm font-medium text-white">
                      Consultations
                    </p>
                  </div>
                  <Sparkles className="size-4 text-cyan-300" />
                </div>

                <div className="space-y-3">
                  {[
                    ["09:00", "Discovery call", "Open"],
                    ["11:30", "Team review", "Booked"],
                    ["14:00", "Strategy session", "Open"],
                    ["16:30", "Client check-in", "Held"],
                  ].map(([time, title, status]) => (
                    <div
                      key={time}
                      className="flex items-center justify-between rounded-2xl border border-white/10 bg-slate-900/70 px-3 py-3"
                    >
                      <div>
                        <p className="text-sm font-medium text-white">
                          {title}
                        </p>
                        <p className="text-xs text-slate-400">{time}</p>
                      </div>
                      <span className="rounded-full bg-white/5 px-2.5 py-1 text-[0.7rem] text-slate-300">
                        {status}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="rounded-[1.5rem] border border-white/10 bg-[linear-gradient(180deg,rgba(255,255,255,0.08),rgba(255,255,255,0.03))] p-4">
                <div className="mb-4 flex items-center justify-between">
                  <div>
                    <p className="text-xs uppercase tracking-[0.25em] text-slate-500">
                      Booking flow
                    </p>
                    <p className="mt-1 text-sm font-medium text-white">
                      From selection to confirmation
                    </p>
                  </div>
                  <ArrowRight className="size-4 text-sky-300" />
                </div>

                <div className="rounded-[1.5rem] border border-white/10 bg-slate-950/70 p-4">
                  <div className="grid gap-2 sm:grid-cols-2">
                    {[
                      ["Calendar sync", "Availability updates in real time"],
                      ["Instant booking", "One click reserves the slot"],
                      ["Google Meet", "Auto-generated meeting link"],
                      ["Notifications", "Guests and hosts stay aligned"],
                    ].map(([title, copy]) => (
                      <div
                        key={title}
                        className="rounded-2xl border border-white/10 bg-white/[0.03] p-3"
                      >
                        <div className="mb-2 flex size-8 items-center justify-center rounded-xl bg-cyan-400/10 text-cyan-300">
                          <CheckCircle2 className="size-4" />
                        </div>
                        <p className="text-sm font-medium text-white">
                          {title}
                        </p>
                        <p className="mt-1 text-xs leading-5 text-slate-400">
                          {copy}
                        </p>
                      </div>
                    ))}
                  </div>

                  <div className="mt-4 rounded-2xl border border-cyan-400/20 bg-cyan-400/10 p-4 text-sm text-cyan-50">
                    <div className="flex items-center gap-2 font-medium text-white">
                      <Video className="size-4" />
                      Meeting ready
                    </div>
                    <p className="mt-2 text-cyan-50/80">
                      MeetMint creates the Google Meet link automatically and
                      adds it to the invite.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-[linear-gradient(180deg,rgba(15,23,42,0.7),rgba(2,6,23,0.95))] p-5 sm:p-6">
            <div className="rounded-[1.75rem] border border-white/10 bg-white/[0.04] p-4">
              <div className="mb-4 flex items-center justify-between text-sm text-slate-300">
                <span>Month view</span>
                <span className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-xs">
                  May 2026
                </span>
              </div>

              <div className="grid grid-cols-7 gap-2">
                {["S", "M", "T", "W", "T", "F", "S"].map((day) => (
                  <div
                    key={day}
                    className="pb-2 text-center text-[0.65rem] uppercase tracking-[0.25em] text-slate-500"
                  >
                    {day}
                  </div>
                ))}
                {Array.from({ length: 35 }, (_, index) => {
                  const highlighted = [
                    6, 8, 11, 14, 17, 21, 24, 28, 30, 32,
                  ].includes(index);
                  const booked = [9, 18, 29].includes(index);

                  return (
                    <div
                      key={index}
                      className={`aspect-square rounded-2xl border p-2 text-xs transition-transform duration-300 hover:-translate-y-0.5 ${
                        highlighted
                          ? booked
                            ? "border-cyan-400/30 bg-cyan-400/15 text-white"
                            : "border-emerald-400/25 bg-emerald-400/10 text-emerald-100"
                          : "border-white/5 bg-white/[0.03] text-slate-500"
                      }`}
                    >
                      <div className="flex h-full flex-col justify-between">
                        <span>{index + 1}</span>
                        {highlighted && (
                          <span className="h-1.5 w-1.5 rounded-full bg-current opacity-80" />
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <div className="mt-4 grid gap-4 sm:grid-cols-2">
              <div className="rounded-[1.5rem] border border-white/10 bg-white/[0.04] p-4">
                <p className="text-xs uppercase tracking-[0.25em] text-slate-500">
                  Efficiency
                </p>
                <p className="mt-3 text-3xl font-semibold text-white">-73%</p>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Less scheduling back-and-forth after switching to a single
                  booking flow.
                </p>
              </div>
              <div className="rounded-[1.5rem] border border-white/10 bg-white/[0.04] p-4">
                <p className="text-xs uppercase tracking-[0.25em] text-slate-500">
                  Response time
                </p>
                <p className="mt-3 text-3xl font-semibold text-white">
                  Instant
                </p>
                <p className="mt-2 text-sm leading-6 text-slate-400">
                  Guests can book the first available slot without waiting for a
                  reply.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function FeatureCard({
  icon: Icon,
  title,
  description,
}: {
  icon: React.ElementType;
  title: string;
  description: string;
}) {
  return (
    <article className="group relative overflow-hidden rounded-[1.5rem] border border-slate-200/80 bg-white/80 p-6 shadow-[0_12px_40px_rgba(15,23,42,0.06)] backdrop-blur transition-all duration-300 hover:-translate-y-1 hover:border-slate-300 hover:shadow-[0_24px_80px_rgba(15,23,42,0.12)] dark:border-white/10 dark:bg-white/[0.04]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(56,189,248,0.15),transparent_38%)] opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
      <div className="relative">
        <div className="mb-5 flex size-12 items-center justify-center rounded-2xl border border-slate-200 bg-slate-950 text-white shadow-lg shadow-slate-950/10 dark:border-white/10 dark:bg-white/10">
          <Icon className="size-5" />
        </div>
        <h3 className="text-lg font-semibold tracking-tight text-slate-950 dark:text-white">
          {title}
        </h3>
        <p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">
          {description}
        </p>
      </div>
    </article>
  );
}

export default function Home() {
  return (
    <div className="min-h-screen bg-[radial-gradient(circle_at_top,rgba(15,23,42,0.08),transparent_42%),linear-gradient(180deg,#f8fafc_0%,#eef2ff_36%,#ffffff_100%)] text-slate-950 dark:bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.18),transparent_32%),linear-gradient(180deg,#020617_0%,#0f172a_100%)] dark:text-white">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-white/75 backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/70">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link
            href="/"
            className="flex items-center gap-3 transition-opacity hover:opacity-80"
          >
            <span className="flex size-10 items-center justify-center rounded-2xl bg-slate-950 text-sm font-semibold text-white shadow-lg shadow-slate-950/15 dark:bg-white dark:text-slate-950">
              C
            </span>
            <span className="text-lg font-semibold tracking-tight">
              MeetMint
            </span>
          </Link>

          <nav className="flex items-center gap-3 sm:gap-5">
            <Link
              href="/pricing"
              className="text-sm font-medium text-slate-600 transition-colors hover:text-slate-950 dark:text-slate-300 dark:hover:text-white"
            >
              Pricing
            </Link>
            <Link
              href="/auth/login"
              className="hidden rounded-full border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition-all hover:border-slate-400 hover:bg-slate-100 sm:inline-flex dark:border-white/10 dark:text-slate-200 dark:hover:bg-white/10"
            >
              Sign In
            </Link>
            <Link
              href="/auth/register"
              className="inline-flex rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white shadow-[0_12px_30px_rgba(15,23,42,0.22)] transition-all hover:-translate-y-0.5 hover:bg-slate-800 dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200"
            >
              Get Started
            </Link>
          </nav>
        </div>
      </header>

      <main className="pt-28 sm:pt-32">
        <section className="relative overflow-hidden">
          <div className="absolute inset-x-0 top-0 -z-10 h-[36rem] bg-[radial-gradient(circle_at_top,rgba(59,130,246,0.14),transparent_40%),radial-gradient(circle_at_20%_30%,rgba(16,185,129,0.10),transparent_25%),radial-gradient(circle_at_80%_20%,rgba(99,102,241,0.12),transparent_28%)]" />
          <div className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 sm:pb-28 lg:px-8">
            <div className="mx-auto max-w-4xl text-center">
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-slate-300 bg-white/75 px-4 py-1.5 text-sm font-medium text-slate-700 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/5 dark:text-slate-200">
                <Sparkles className="size-4 text-sky-500" />
                Scheduling that feels effortless
              </div>

              <h1 className="text-balance text-5xl font-semibold tracking-tight text-slate-950 sm:text-6xl lg:text-7xl dark:text-white">
                Eliminate scheduling back-and-forth with a booking flow people
                actually finish.
              </h1>

              <p className="mx-auto mt-6 max-w-2xl text-pretty text-lg leading-8 text-slate-600 sm:text-xl dark:text-slate-300">
                MeetMint syncs with Google Calendar, shows real-time
                availability, and lets guests book instantly while automatically
                generating the right meeting details.
              </p>

              <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
                <Link
                  href="/auth/register"
                  className="inline-flex w-full items-center justify-center rounded-full bg-slate-950 px-7 py-3.5 text-base font-semibold text-white shadow-[0_16px_40px_rgba(15,23,42,0.24)] transition-all hover:-translate-y-0.5 hover:bg-slate-800 sm:w-auto dark:bg-white dark:text-slate-950 dark:hover:bg-slate-200"
                >
                  Create account
                  <ArrowRight className="ml-2 size-4" />
                </Link>
                <Link
                  href="/auth/login"
                  className="inline-flex w-full items-center justify-center rounded-full border border-slate-300 bg-white/80 px-7 py-3.5 text-base font-semibold text-slate-900 shadow-sm transition-all hover:-translate-y-0.5 hover:border-slate-400 hover:bg-white sm:w-auto dark:border-white/10 dark:bg-white/5 dark:text-white dark:hover:bg-white/10"
                >
                  Sign in
                </Link>
              </div>
            </div>

            <div className="mt-14 sm:mt-18">
              <BookingVisual />
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-20 lg:px-8">
          <div className="max-w-2xl">
            <p className="text-sm font-semibold uppercase tracking-[0.28em] text-slate-500 dark:text-slate-400">
              Features
            </p>
            <h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl dark:text-white">
              Everything you need to turn availability into revenue.
            </h2>
          </div>

          <div className="mt-10 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">
            {featureCards.map((card) => (
              <FeatureCard key={card.title} {...card} />
            ))}
          </div>
        </section>

        <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-20 lg:px-8">
          <div className="grid gap-8 lg:grid-cols-[1fr_1.05fr] lg:items-center">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.28em] text-slate-500 dark:text-slate-400">
                Integrations
              </p>
              <h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-950 sm:text-4xl dark:text-white">
                Google Calendar sync and Google Meet generation, built in.
              </h2>
              <p className="mt-5 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">
                MeetMint keeps the source of truth in your calendar, then
                creates the meeting link, writes the event details, and updates
                availability the moment a booking changes.
              </p>

              <div className="mt-8 space-y-4">
                {integrationBullets.map((bullet) => (
                  <div
                    key={bullet}
                    className="flex items-start gap-3 rounded-2xl border border-slate-200 bg-white/80 p-4 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/[0.04]"
                  >
                    <CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-500" />
                    <p className="text-sm leading-6 text-slate-700 dark:text-slate-200">
                      {bullet}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            <div className="relative">
              <div className="absolute -inset-4 rounded-[2rem] bg-[radial-gradient(circle_at_top,rgba(34,197,94,0.14),transparent_40%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,0.16),transparent_35%)] blur-2xl" />
              <div className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-white/85 p-5 shadow-[0_24px_80px_rgba(15,23,42,0.10)] backdrop-blur dark:border-white/10 dark:bg-slate-950/75">
                <div className="flex items-center justify-between border-b border-slate-200 pb-4 text-sm dark:border-white/10">
                  <div>
                    <p className="font-semibold text-slate-950 dark:text-white">
                      Google Calendar
                    </p>
                    <p className="text-slate-500 dark:text-slate-400">
                      Connected account preview
                    </p>
                  </div>
                  <span className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-300">
                    Synced
                  </span>
                </div>

                <div className="mt-5 grid gap-4 lg:grid-cols-[1.05fr_0.95fr]">
                  <div className="rounded-[1.5rem] border border-slate-200 bg-slate-50 p-4 dark:border-white/10 dark:bg-white/[0.04]">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-xs uppercase tracking-[0.25em] text-slate-500 dark:text-slate-400">
                          Calendar preview
                        </p>
                        <p className="mt-1 text-sm font-semibold text-slate-950 dark:text-white">
                          June availability
                        </p>
                      </div>
                      <div className="rounded-full border border-slate-200 bg-white px-3 py-1 text-xs text-slate-600 dark:border-white/10 dark:bg-white/5 dark:text-slate-300">
                        14 open
                      </div>
                    </div>

                    <div className="mt-4 grid grid-cols-7 gap-2">
                      {Array.from({ length: 28 }, (_, index) => {
                        const isBusy = [2, 5, 9, 12, 16, 18, 22, 25].includes(
                          index,
                        );
                        const isOpen = [3, 4, 10, 11, 17, 19, 23].includes(
                          index,
                        );

                        return (
                          <div
                            key={index}
                            className={`aspect-square rounded-2xl border text-[0.7rem] font-medium transition-transform hover:-translate-y-0.5 ${
                              isBusy
                                ? "border-cyan-200 bg-cyan-100 text-cyan-900 dark:border-cyan-400/20 dark:bg-cyan-400/10 dark:text-cyan-100"
                                : isOpen
                                  ? "border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-400/20 dark:bg-emerald-400/10 dark:text-emerald-100"
                                  : "border-slate-200 bg-white text-slate-300 dark:border-white/10 dark:bg-white/[0.02] dark:text-slate-600"
                            }`}
                          >
                            <div className="flex h-full flex-col justify-between p-2">
                              <span>{index + 1}</span>
                              {(isBusy || isOpen) && (
                                <span className="h-1.5 w-1.5 rounded-full bg-current" />
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  <div className="space-y-4 rounded-[1.5rem] border border-slate-200 bg-slate-950 p-4 text-white dark:border-white/10">
                    <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
                      <div className="flex items-center justify-between">
                        <p className="text-sm font-medium">
                          Booking confirmation
                        </p>
                        <Video className="size-4 text-sky-300" />
                      </div>
                      <div className="mt-4 space-y-3 text-sm text-slate-300">
                        <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2">
                          <span>Google Meet</span>
                          <span className="text-emerald-300">Created</span>
                        </div>
                        <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2">
                          <span>Calendar event</span>
                          <span className="text-cyan-300">Synced</span>
                        </div>
                        <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2">
                          <span>Guest reminder</span>
                          <span className="text-white">Queued</span>
                        </div>
                      </div>
                    </div>

                    <div className="rounded-2xl border border-white/10 bg-[linear-gradient(135deg,rgba(59,130,246,0.22),rgba(16,185,129,0.16))] p-4">
                      <p className="text-xs uppercase tracking-[0.25em] text-slate-300">
                        Result
                      </p>
                      <p className="mt-2 text-lg font-semibold text-white">
                        One booking creates the whole meeting stack.
                      </p>
                      <p className="mt-2 text-sm leading-6 text-slate-200/80">
                        Calendar event, Meet link, and guest notification are
                        assembled automatically.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-20 lg:px-8">
          <div className="rounded-[2rem] border border-slate-200 bg-slate-950 px-6 py-14 text-center text-white shadow-[0_24px_100px_rgba(15,23,42,0.18)] sm:px-10 dark:border-white/10">
            <p className="text-sm font-semibold uppercase tracking-[0.28em] text-slate-400">
              Ready to launch
            </p>
            <h2 className="mx-auto mt-4 max-w-3xl text-3xl font-semibold tracking-tight sm:text-5xl">
              Start with MeetMint and turn every available slot into a clean
              booking experience.
            </h2>
            <p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">
              Give visitors a polished path from interest to confirmed meeting
              with no manual follow-up.
            </p>
            <div className="mt-8 flex justify-center">
              <Link
                href="/auth/register"
                className="inline-flex items-center justify-center rounded-full bg-white px-7 py-3.5 text-base font-semibold text-slate-950 shadow-[0_16px_40px_rgba(255,255,255,0.18)] transition-all hover:-translate-y-0.5 hover:bg-slate-100"
              >
                Get started
              </Link>
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-slate-200/80 bg-white/70 backdrop-blur dark:border-white/10 dark:bg-slate-950/70">
        <div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8">
          <div>
            <p className="text-lg font-semibold text-slate-950 dark:text-white">
              MeetMint
            </p>
            <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
              Premium scheduling for teams that want fewer meetings about
              meetings.
            </p>
          </div>

          <Link
            href="/pricing"
            className="text-sm font-medium text-slate-600 transition-colors hover:text-slate-950 dark:text-slate-300 dark:hover:text-white"
          >
            Pricing
          </Link>
        </div>
      </footer>
    </div>
  );
}
